# Site
name: "데이트팝 기술블로그"
title: "데이트팝 기술블로그"
# description: ""
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/logo.jpg'
baseurl: 'https://blog.datepop.co.kr'
# google_analytics: ''
disqus: 'datepop-tech-blog'
# mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Changyun:
    name: 이창윤
    display_name: 이창윤
    email: datepop21@gmail.com
    githubuid: 57675145
    web: https://www.linkedin.com/in/zerostrength
    description: "백엔드 개발자"
    linkedin: https://www.linkedin.com/in/zerostrength
  Coldzero:
    name: 이찬영
    display_name: 이찬영
    githubuid: 89123869
    email: cyl0504@gmail.com
    web: https://velog.io/@coldzero
    description: "백엔드 개발자"
  ZeroDeg:
    name: 장영도
    display_name: 장영도
    githubuid: 19370688
    email: zerodeg.date@gmail.com
    web: https://github.com/ok0035
    description: "안드로이드 개발자"
  Suho:
    name: 이수호
    display_name: 이수호
    githubuid: 28211989
    email: suho.datepop@gmail.com
    web: https://github.com/suhoeel
    description: "안드로이드 개발자"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: 
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
