version: "3"

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --force_polling --drafts --livereload --trace --baseUrl '/'
    ports:
      - 4000:4000
      - 35729:35729
      - 80:4000
    volumes:
      - .:/srv/jekyll
    restart: always
